name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Install latest gcc
      run: |
        sudo apt-get update
        sudo apt-get install gcc-11.2
      
    - name: Install dependencies from conan
      run: |
        pip install conan
        mkdir ${{github.workspace}}/build
        conan install -if ${{github.workspace}}/build ${{github.workspace}} --build missing
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
